{{ if .Values.deployHostManifests }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
  {{- include "servicechain.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
