{{ if .Values.deployHostManifests }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "nvidia-k8s-ipam.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/description: |
      This deployment launches the nv-ipam controller for nv-ipam.
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: controller
  template:
    metadata:
      labels:
        name: controller
    spec:
      automountServiceAccountToken: false
      priorityClassName: system-cluster-critical
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: "{{ .Values.nvIpam.image.repository }}:{{ .Values.nvIpam.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nvIpam.pullPolicy }}
          command: [ "/ipam-controller" ]
          args:
            - --leader-elect=true
            - --leader-elect-namespace=$(POD_NAMESPACE)
            - --ippools-namespace=$(POD_NAMESPACE)
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.nvIpam.controller.resources | nindent 12 }}
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      securityContext:
        runAsNonRoot: true
{{ end }}
