{{ if .Values.deployHostManifests }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-k8s-ipam.labels" . | nindent 4 }}
{{- end }}
