apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
  {{- include "cni-installer.labels" . | nindent 4 }}
  annotations:
    {{- include "cni-installer.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: cni-installer
  template:
    metadata:
      labels:
        name: cni-installer
        {{- include "cni-installer.labels" . | nindent 8 }}
      annotations:
        {{- include "cni-installer.annotations" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      serviceAccountName: {{ include "cni-installer.fullname" . }}
      containers:
      - args: {{ toJson .Values.cniInstaller.args }}
        command:
        - /cni-installer
        name: cni-installer
        image: {{ .Values.cniInstaller.image.repository }}:{{ .Values.cniInstaller.image.tag | default .Chart.AppVersion }}
        resources: {{- toYaml .Values.cniInstaller.resources | nindent 10 }}
        securityContext:
          runAsUser: 0
          # Needs to run as privileged, otherwise writing to the cnibin direcctory on RHCOS is not permitted due to selinux.
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /opt/cni/bin
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      securityContext:
        runAsNonRoot: false
      volumes:
      - name: cnibin
        hostPath:
          path: {{ .Values.cniBinDir }}
          type: Directory
