####################
### DPF contract ###
####################

# configuration for the service
serviceDaemonSet:
  # selects nodes on which this service will run by label. Can be set in DPUService `.spec.serviceDaemonSet.nodeSelector`
  # nodeSelector:
  #   nodeSelectorTerms:
  #   - matchExpressions:
  #       - key: dpu
  #         operator: In
  #         values:
  #           - dpu
  # labels on the DaemonSet and pod template. Can be set in DPUService `.spec.serviceDaemonSet.labels`
  labels: {}
  # annotations on the DaemonSet and pod template. Can be set in DPUService `.spec.serviceDaemonSet.annotations`
  annotations: {}
  # updateStrategy on the DaemonSet. Can be set in DPUService `.spec.serviceDaemonSet.updateStrategy.`
  updateStrategy: {}
  #  type: RollingUpdate
  #  rollingUpdate:
  #    maxUnavailable: 1
  # resources on the DaemonSet and pod template. Can be set in DPUService `.spec.serviceDaemonSet.resources`
  resources: {}

# default imagePullSecrets
imagePullSecrets: []


# Note: This chart includes multiple components but is designed to deploy only one at a time.
# By default, all components are disabled.
# To deploy a specific component, explicitly set the "enabled" flag to true.

#######################################
### Components for the host cluster ###
#######################################
host:
  ### snap-csi-plugin ###
  snapCsiPlugin:
    # enable deployment of the snap-csi-plugin component
    # Note: Only one component can be enabled at a time.
    enabled: false
    # name of the CSI plugin, this name is returned by the plugin in response to GetPluginInfo call.
    # this value should be used as a value for the StorageClass.provisioner field
    name: "csi.snap.nvidia.com"
    # emulation mode for the plugin. Valid options are "nvme" and "virtiofs".
    # In "nvme" mode, the plugin creates block DPUVolumes and exposes them as emulated NVMe devices.
    # In "virtiofs" mode, the plugin creates filesystem DPUVolumes and exposes them as VirtioFS devices.
    emulationMode: "nvme"
    controller:
      # enable deployment of the controller part of snap-csi-plugin
      enabled: false
      # imagePullSecrets to add to the controller Pod spec,
      # if not set use .Values.imagePullSecrets
      imagePullSecrets: []
      # count of replicas for controller pod
      replicas: 1
      # configuration for plugin container
      plugin:
        # args for the plugin container
        args:
          # log level for the plugin container
          logLevel: 2
        # image settings for plugin container
        image:
          repository: example.com/storage-system
          tag: v0.1.0
        # imagePullPolicy for plugin image
        imagePullPolicy: IfNotPresent
        # securityContext for plugin container
        securityContext:
          allowPrivilegeEscalation: false
        # resources for plugin container
        resources: {}
      externalProvisioner:
        image:
          # image settings for external-provisioner container
          repository: "registry.k8s.io/sig-storage/csi-provisioner"
          # tag for csi-provisioner image
          # Note: v6.x requires Kubernetes 1.34+
          tag: v5.3.0
        # imagePullPolicy for external-provisioner image
        imagePullPolicy: IfNotPresent
        # securityContext for external-provisioner container
        securityContext:
          allowPrivilegeEscalation: false
        # resources for external container
        resources: {}
      externalAttacher:
        image:
          # image settings for external-attacher container
          repository: "registry.k8s.io/sig-storage/csi-attacher"
          # tag for csi-attacher image
          tag: v4.11.0
        # imagePullPolicy for external-attacher image
        imagePullPolicy: IfNotPresent
        # securityContext for external-attacher container
        securityContext:
          allowPrivilegeEscalation: false
        # resources for external container
        resources: {}
      livenessProbe:
        image:
          # image settings for livenessprobe container
          repository: "registry.k8s.io/sig-storage/livenessprobe"
          # tag for liveness-probe image
          tag: v2.18.0
        # imagePullPolicy for liveness-probe image
        imagePullPolicy: IfNotPresent
        # securityContext for liveness-probe container
        securityContext:
          allowPrivilegeEscalation: false
        # resources for liveness-probe container
        resources: {}
      # podAnnotations to add to the Pod spec
      podAnnotations: {}
      # podLabels to add to the Pod spec
      podLabels: {}
      # podSecurityContext to add to the Pod spec
      podSecurityContext: {}
      #  runAsNonRoot: true
      # nodeSelector to add to the Pod spec
      nodeSelector: {}
      # tolerations to add to the Pod spec
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      # affinity to add to the Pod spec
      affinity: {}
    node:
      # enable deployment of the node part of snap-csi-plugin
      enabled: false
      # use hostNetwork for the plugin pod
      hostNetwork: false
      config:
        # pci device ID of the snap controller device
        snapControllerDeviceId: "6001"
        # max number of volumes that can be published to a node,
        # the value allows to override the auto-discovered value if it is not accurate.
        # the value is set to 0 by default, which means that the auto-discovered value will be used
        maxVolumesPerNode: 0
        # controls if NVMe driver should be loaded or not during initialization of the plugin, has meaning only for nvme emulation mode
        nvmeLoadDriver: true
        # controls if NVMe VFs should be created or not during initialization of the plugin, has meaning only for nvme emulation mode
        nvmeCreateVFs: true
        # name of the virtiofs fs type, this value is used in mount command, has meaning only for virtiofs emulation mode
        virtiofsFSTypeName: "virtiofs"
        # controls if virtio-pci driver should be loaded or not during initialization of the plugin, has meaning only for virtiofs emulation mode
        virtiofsLoadDriver: true
        # port for the liveness probe, you may need to change it when pod is running with hostNetwork: true
        livenessProbePort: 29808
      # imagePullSecrets to add to the controller Pod spec,
      # if not set use .Values.imagePullSecrets
      imagePullSecrets: []
      # configuration for plugin container
      plugin:
        # args for the plugin container
        args:
          # log level for the plugin container
          logLevel: 2
        # image settings for plugin container
        image:
          repository: example.com/storage-host
          tag: v0.1.0
        # imagePullPolicy for plugin image
        imagePullPolicy: IfNotPresent
        # securityContext for plugin container
        securityContext:
          runAsUser: 0
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
      livenessProbe:
        image:
          # liveness-probe image name
          repository: "registry.k8s.io/sig-storage/livenessprobe"
          # tag for liveness-probe image
          tag: v2.18.0
        # imagePullPolicy for liveness-probe image
        imagePullPolicy: IfNotPresent
        # securityContext for liveness-probe container
        securityContext:
          allowPrivilegeEscalation: false
        # resources for liveness-probe container
        resources: {}
      nodeDriverRegistrar:
        image:
          # node-driver-registrar image name
          repository: "registry.k8s.io/sig-storage/csi-node-driver-registrar"
          # tag for node-driver-registrar image
          tag: v2.16.0
        # imagePullPolicy for liveness-probe image
        imagePullPolicy: IfNotPresent
        # securityContext for node-driver-registrar container
        securityContext:
          allowPrivilegeEscalation: false
        # resources for plugin container
        resources: {}
      # kubelet dir on the host
      kubeletDir: /var/lib/kubelet
      # podSecurityContext to add to the Pod spec
      podSecurityContext: {}
      #  runAsNonRoot: true
      # tolerations to add to the Pod spec
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists

  ### snap-host-controller ###
  snapHostController:
    # enable deployment of the snap-host-controller component
    # Note: Only one component can be enabled at a time.
    enabled: false
    config:
      # required, namespace in the DPU cluster to create Volume and VolumeAttachment objects
      targetNamespace: ""
      # namespace in which controller will reconcile resources, if not set, defaults to deployment namespace
      namespace: ""
    # image settings
    image:
      repository: example.com/storage-system
      tag: v0.1.0
    imagePullSecrets: []
    # count of replicas for controller pod
    replicas: 1
    # podAnnotations to add to the Pod spec
    podAnnotations: {}
    # podLabels to add to the Pod spec
    podLabels: {}
    # podSecurityContext to add to the Pod spec
    podSecurityContext:
      runAsNonRoot: true
    securityContext:
      runAsUser: 65532
      privileged: false
    # nodeSelector to add to the Pod spec
    nodeSelector: {}
    # tolerations to add to the Pod spec
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
    # affinity to add to the Pod spec
    affinity: {}


#######################################
### Components for the DPU cluster ###
#######################################
dpu:
  deployCrds: false
  ### snap-node-driver ###
  snapNodeDriver:
    # enable deployment of the snap-node-driver component
    # Note: Only one component can be enabled at a time.
    enabled: false
    tolerations: []
    image:
      repository: example.com/storage-system
      tag: v0.1.0
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    securityContext:
      runAsUser: 0
    env: []

  ### block-storage-vendor-dpu-plugin ###
  blockStorageVendorDpuPlugin:
    # enable deployment of the block-storage-vendor-dpu-plugin component
    # Note: Only one component can be enabled at a time.
    enabled: false
    config:
      pluginName: "nvidia-block"
      providerName: "nvidia"
    tolerations: []
    image:
      repository: example.com/storage-system
      tag: v0.1.0
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    securityContext:
      runAsUser: 0
    env: []

  ### fs-storage-vendor-dpu-plugin ###
  fsStorageVendorDpuPlugin:
    # enable deployment of the fs-storage-vendor-dpu-plugin component
    # Note: Only one component can be enabled at a time.
    enabled: false
    config:
      pluginName: "nvidia-fs"
      providerName: "nvidia"
    tolerations: []
    image:
      repository: example.com/storage-host
      tag: v0.1.0
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    securityContext:
      runAsUser: 0
      privileged: true
    env: []

  ### nfs-storage-vendor-dpu-plugin ###
  nfsStorageVendorDpuPlugin:
    # enable deployment of the nfs-storage-vendor-dpu-plugin component
    # Note: Only one component can be enabled at a time.
    enabled: false
    config:
      pluginName: "nvidia-nfs"
      providerName: "nvidia"
    tolerations: []
    image:
      repository: example.com/storage-system
      tag: v0.1.0
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    securityContext:
      runAsUser: 0
    env: []

  ### doca-snap ###
  docaSnap:
    # enable deployment of the doca-snap component
    # Note: Only one component can be enabled at a time.
    enabled: false
    name: "doca-snap"
    image:
      repository: nvcr.io/nvidia/doca/doca_vfs
      tag: 1.7.0-doca3.4.0
    tolerations: []
    imagePullSecrets: []
    restartPolicy: "Always"
    hostNetwork: false
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      capabilities:
        add:
          - "IPC_LOCK"
          - "SYS_RAWIO"
          - "SYS_NICE"
    env:
      APP_ARGS: "-m 0xff"
      SNAP_SPDK_SOCK: "/var/lib/nvidia/storage/snap/providers/nvidia/snap.sock"
    snapRpcInitConf: ""
    spdkRpcInitConf: ""
