# This variable controls whether the manifests that are required in the DPUCluster should be deployed or not
deployDPUManifests: false
# This variable controls whether the manifests that are required in the host cluster should be deployed or not
deployHostManifests: false

controllerManager:
  manager:
    args:
    - --leader-elect
    - --leader-election-namespace=$(POD_NAMESPACE)
    containerSecurityContext:
      runAsUser: 65532
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: example.com/dpf-system
      tag: v0.1.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
serviceAccount:
  annotations: {}
  labels: {}
  name: null
imagePullSecrets: []
volumes: []
env: []
volumeMounts: []
rbac:
  serviceAccounts: []