## Images built as part of the DPF release.
dmsImage: example.com/hostdriver:v0.1.0
dpfSystemImage: example.com/dpf-system:v0.1.0
ovsCniImage: example.com/ovs-cni-plugin:v0.1.0
bfbRegistryImage: example.com/bfb-registry:v0.1.0
dpfStorageSystemImage: example.com/storage-system:v0.1.0
dpfStorageHostImage: example.com/storage-host:v0.1.0
cniInstallerImage: example.com/dpf-cni-installer:v0.1.0
keepalivedImage: example.com/dpf-keepalived:v0.1.0

## Helm charts built as part of the DPF release.
dpuNetworkingHelmChart: oci://example.com/dpu-networking:v0.1.0

## Extra dependencies that are directly refered by the DPF binaries, but not built as part of the DPF release.
nodeSRIOVDevicePluginImage: nvcr.io/nvidia/mellanox/sriov-network-device-plugin:network-operator-v26.1.0
