# This variable controls whether the manifests that are required in the DPUCluster should be deployed or not
deployDPUManifests: false
# This variable controls whether the manifests that are required in the host cluster should be deployed or not
deployHostManifests: false

serviceAccount:
  name: null
imagePullSecrets: []
volumes: []
env: []
volumeMounts: []
rbac:
  serviceAccounts: []
nvIpam:
  image:
    repository: ghcr.io/mellanox/nvidia-k8s-ipam
    tag: v0.4.0@sha256:4b984dd345754e28ff964a209d76bff71ed31bb392b25aa5ddccf3925ac4e2ce
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        memory: 300Mi
  node:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 300m
        memory: 400Mi
  nameOverride: ""
  fullnameOverride: ""
  pullPolicy: IfNotPresent

cniBinDir: /opt/cni/bin
cniConfDir: /etc/cni/net.d
