- groupVersionKind:
    group: provisioning.dpu.nvidia.com
    kind: DPUSet
    version: v1alpha1
  labelsFromPath:
    name:
      - metadata
      - name
    namespace:
      - metadata
      - namespace
    uid:
      - metadata
      - uid
  metricNamePrefix: dpuset
  metrics:
    - name: created
      help: Unix creation timestamp.
      each:
        gauge:
          path:
            - metadata
            - creationTimestamp
        type: Gauge
    - name: info
      help: Information about a DPUSet.
      each:
        type: Info
        info:
          labelsFromPath:
            name:
              - metadata
              - name
            strategy_type:
              - spec
              - strategy
              - type
    - name: status_dpu_statistics
      help: Count of DPUs per phase in the DPUSet.
      each:
        type: Gauge
        gauge:
          labelsFromPath:
            phase:
              - ""
          path:
            - status
            - dpuStatistics
          valueFrom:
            - ""
    - name: status_conditions
      help: The condition of a DPUSet.
      each:
        stateSet:
          labelName: status
          labelsFromPath:
            type:
              - type
          list:
            - 'True'
            - 'False'
            - Unknown
          path:
            - status
            - conditions
          valueFrom:
            - status
        type: StateSet
    - name: status_condition_last_transition_time
      help: The condition last transition time of a DPUSet.
      each:
        gauge:
          nilIsZero: true
          labelsFromPath:
            type:
              - type
            status:
              - status
          path:
            - status
            - conditions
          valueFrom:
            - lastTransitionTime
        type: Gauge
